#INSERTS
#INSETIR ARTISTAS PRIMEIRO

#ARTISTA
INSERT INTO ARTISTA VALUES('DKNAKJDNA', '2010-08-15', 'DSFDSFDS','SDFD','MKSADMNAS','ANSVDGQ');
INSERT INTO ARTISTA VALUES('ASDQJIWBDIQWJ', '1982-11-11','QWEQW','ASBSDVQ','SVWQCFG','CWSQGHCS');
INSERT INTO ARTISTA VALUES('AEQEBKJWE0', '1925-02-25', 'SAKDBQWJ','WQFECQWGEH','WBQNE','MWQEWQE');

#OBJETOS_ARTE
INSERT INTO OBJETO_ARTE VALUES(NULL,'A', 'B', '1970-12-12', 'C', 'D', 'E','F','G','DKNAKJDNA'); #COLECOES PERMANENTES
INSERT INTO OBJETO_ARTE VALUES(NULL,'SALKN', 'DJKFDS', '1930-04-10', 'DFJSDS','KNSFDKJFS', 'ESCULTURA', 'ASDQJIWBDIQWJ','DBSDFUHY','ASDQJIWBDIQWJ'); #ESCULTURAS     
INSERT INTO OBJETO_ARTE VALUES(NULL,'WQJEBNKQ', 'IJTGFID', '1980-11-28', 'FBDSJFHD','KFJDLGKD', 'OUTROS','JDFSHKFJS','BFDSMFNKL', NULL); #OUTROS
INSERT INTO OBJETO_ARTE VALUES(NULL,'FDJKBEKJ', 'DBSFJSDBF', '1952-09-05','BAJKDASJB ', 'EPOROWIE', 'EMPRESTADO', 'JKDFHSKJ','DKSNFKSD','AEQEBKJWE0'); #EMPRESTADO
INSERT INTO OBJETO_ARTE VALUES(NULL,'ASJKDBAKJH', 'FD SNSB NMF', '1979-01-19', 'DSVFEWF','NDSBJ','PINTURA','DFJSNFKJDSN','NDKJSNF', 'ASDQJIWBDIQWJ'); #PINTURA
INSERT INTO OBJETO_ARTE VALUES(NULL,'ASJKDBAKJH', 'FD SNSB NMF', '1994-09-08', 'DSVFEWF','NDSBJ','EXPOSICAO','DFJSNFKJDSN','NDKJSNF', 'DKNAKJDNA'); #EXPOSICAO

#COLECAO PERMANENTE
INSERT INTO COLECAO_PERMANENTE VALUES (666, 1, 1);
INSERT INTO COLECAO_PERMANENTE VALUES (1000, 1, 1);
INSERT INTO COLECAO_PERMANENTE VALUES (444, 1, 1);
INSERT INTO COLECAO_PERMANENTE VALUES (100, 0, 3);
INSERT INTO COLECAO_PERMANENTE VALUES (704,1, 5);

#ESCULTURA
INSERT INTO ESCULTURA VALUES(1023,21,'DFKLNG0',2);

#OUTROS
INSERT INTO OUTROS VALUES('DSKJDSD', 3);

#EMPRESTADO
INSERT INTO EMPRESTADO VALUES ('2012-12-20', '2014-12-21', 4, NULL);
INSERT INTO EMPRESTADO VALUES ('2006-12-20', '2011-12-10', 3, 'SADAKSJD');
INSERT INTO EMPRESTADO VALUES ('2012-12-24', '2014-01-08', 1, 'DFNFKJW');
INSERT INTO EMPRESTADO VALUES ('2018-05-24', '2020-04-20', 1, 'SADAKSJD');
#PINTURA
INSERT INTO PINTURA VALUES ( 'NDFSDJK', 'DMSANMAS', 5);

#EXPOSICOES
INSERT INTO EXPOSICOES VALUES('DASKFABSKJ', '2010-11-02','2012-06-11');
INSERT INTO EXPOSICOES VALUES('SADQWD','2011-11-20','2012-03-10');
INSERT INTO EXPOSICOES VALUES('JSABNDKJ', '2015/06/29','2019/07/23');

#COLECOES
INSERT INTO COLECOES VALUES('SADAKSJD', 'DFWEWEF','DWDQWEQWEWQE0','SDSAJD QWWW', '(11)92812-2822','DKAJDAS');
INSERT INTO COLECOES VALUES('DFNFKJW', 'FWE HJFBW','DFNJKKWJ','DFVS MKNFN', '(11)92856-2822','34RJKPORJK');

#PARTICIPA
INSERT INTO PARTICIPA VALUES(1,'SADQWD');
INSERT INTO PARTICIPA VALUES(3,'DASKFABSKJ');
INSERT INTO PARTICIPA VALUES(6,'SADQWD');




